# -*- coding: utf-8 -*-
"""Python_PowderXray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141c4vgXjjt4Z2voUi5VYxwvt-lgfgugg
"""

!pip install pymatgen

import pymatgen
from pymatgen.core import Structure
from pymatgen.analysis.diffraction.xrd import XRDCalculator
from pymatgen.util.plotting import pretty_plot

# Load or create a crystal structure
# Example: Load a structure from a CIF file
structure = Structure.from_file("1336_acs+N9+1385.cif")

# Alternatively, you can create a structure manually
# from pymatgen.core import Lattice, Structure
# lattice = Lattice.cubic(4.2)
# structure = Structure(lattice, ["Cs", "Cl"], [[0, 0, 0], [0.5, 0.5, 0.5]])

# Initialize the XRD calculator
xrd_calculator = XRDCalculator(wavelength="CuKa")  # You can also use "CuKa1", "CuKa2", "MoKa", etc.

# Calculate the XRD pattern
xrd_pattern = xrd_calculator.get_pattern(structure, two_theta_range=(0, 90))

# Plot the XRD pattern
plt = pretty_plot(width=8, height=6)
plt.plot(xrd_pattern.x, xrd_pattern.y, label="XRD Pattern")
#plt.xlabel("2θ (degrees)")
plt.set_xlabel("2θ (degrees)")
#plt.ylabel("Intensity (a.u.)")
plt.set_ylabel("Intensity (a.u.)")
plt.set_title("1336_acs+N9+1385 Powder X-ray Diffraction Pattern")
plt.legend()
plt.grid()
#plt.show()

# Print the peaks
print("Peak positions (2θ):", xrd_pattern.x)
print("Peak intensities:", xrd_pattern.y)

# Commented out IPython magic to ensure Python compatibility.
def LoadGraph(name, header):
  structure = Structure.from_file(name)

#   %matplotlib inline
# Alternatively, you can create a structure manually
# from pymatgen.core import Lattice, Structure
# lattice = Lattice.cubic(4.2)
# structure = Structure(lattice, ["Cs", "Cl"], [[0, 0, 0], [0.5, 0.5, 0.5]])

# Initialize the XRD calculator
  xrd_calculator = XRDCalculator(wavelength="CuKa")  # You can also use "CuKa1", "CuKa2", "MoKa", etc.

# Calculate the XRD pattern
  xrd_pattern = xrd_calculator.get_pattern(structure, two_theta_range=(0, 90))

# Plot the XRD pattern

  plt = pretty_plot(width=8, height=6)
  plt.plot(xrd_pattern.x, xrd_pattern.y, label="XRD Pattern")
  #plt.xlabel("2θ (degrees)")
  plt.set_xlabel("2θ (degrees)")
  #plt.ylabel("Intensity (a.u.)")
  plt.set_ylabel("Intensity (a.u.)")
  title = "Powder X-ray Diffraction Pattern -- "+ header
  plt.set_title(title)
  plt.legend()
  plt.grid()
  #plt.show()

# Print the peaks
  '''print("Peak positions (2θ):", xrd_pattern.x)
  print("Peak intensities:", xrd_pattern.y)
  '''
  #png = header + '.png'
  #plt.savefig(png)

import pandas as pd
df = pd.read_csv('qmof.csv')

df.head(3)

df.shape

df = df[df['info.synthesized'] != False]

df.shape

df = df.drop(columns=['info.synthesized'])

import zipfile
import os

# Path to the zip file
zip_file_path = 'relaxed_structures.zip'

# Directory to extract the files to
extract_dir = 'relaxed_structures_extracted'

# Create the extraction directory if it doesn't exist
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir)

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print(f"Files have been extracted to: {extract_dir}")

folder_path = 'relaxed_structures_extracted/relaxed_structures'

# Get a list of all files in the folder
files_in_folder = os.listdir(folder_path)

dfPost = df.copy(deep=True)

dfPost['qmof_id'] = df['qmof_id'] + '.cif'

dfPost.head(3)

dfPost = dfPost[dfPost['qmof_id'].isin(files_in_folder)]

dfPost.shape

output_csv_path = 'RelaxQMOF_SytheFilter (1).csv'
dfPost.to_csv(output_csv_path, index=False)

dfRun = dfPost



import pandas as pd
dfRun = pd.read_csv('dfRun_2529.csv')

Cntr = pd.read_csv('RelaxQMOF_SytheFilter (1).csv')

Cntr.shape

Cntr = dfPost

num = [5846, 10667, 4302, 13258, 8734]
for i in num:
  name = Cntr.iloc[i,0]
  print(name)
  path = 'relaxed_structures_extracted/relaxed_structures/'+ name

  LoadGraph(path, name)

rows_to_delete = []



i=0
for index, row in Cntr.iterrows():
  if (i<500):
    #print(row['qmof_id'])
    path = 'relaxed_structures_extracted/relaxed_structures/'+ row['qmof_id']
    LoadGraph(path, row['qmof_id'])
    #print(row['qmof_id'])
    i=i+1
    rows_to_delete.append(index)

Cntr = Cntr.drop(rows_to_delete)
rows_to_delete=[]

dfRun.shape

dfRun.to_csv('dfRun_2529.csv')

'''
for i in range(10):
  LoadGraph('1091_tfz-d+N131+1821.cif')
  print(i)'''
LoadGraph('1091_tfz-d+N131+1821.cif', '--  Mn-Based MOF')
LoadGraph('11510_dmp+N445+3819.cif', '--  Zn-Based MOF')

LoadGraph('758_tfz-d+N131+1294.cif')